### ISSUE TITLE
governance: Create a new meeting for TAG Chairs/TLs and WG leaders

### ISSUE THREAD

**Issue by helayoty** [cncf/tag-runtime#77]
TAG-Runtime has four active working groups, and a new is about to be created. Hence, we would like to set up a 2-month (maybe quarterly?) meeting with all TAG-Runtime working group chairs/TLs. 
The meeting will be for WGs status update, to discuss the progress, and to help with ongoing issues. 

cc: @kad @elezar @k82cn @stackedsax @kate-goldenring  @cantbewong @dejanb @devigned @endocrimes

```[tasklist]
### Tasks
- [x] Create New WG TL meetings (https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-1942)
- [x] Communicate/Share the details WG Chairs/TLs
- [x] Share status with TOC
```

**Comment by leonardpahlke** [comment]
Great idea, we have smth similar. In TAG ENV we have a 30min meeting with the TAG Leads <> WG Chairs every 2 weeks. We may move to a 4weeks cadence but for now 2 weeks works well 😊

**Comment by helayoty** [comment]
We have the meeting has been set up quarterly. The first meeting is on Wednesday, Sep 27th. Please add it to your agenda from [here](https://tockify.com/cncf.public.events/detail/654/1695223800000?search=TAG-Runtime%20WG%20Leads%20meeting&startms=1695772800000).

 @kad @elezar @k82cn @stackedsax @kate-goldenring @cantbewong @dejanb @devigned @endocrimes
 
 cc: @rajaskakodkar @nikhita @raravena80

**Comment by endocrimes** [comment]
This conflicts with the kubernetes CoCC working meeting, but i'll try to make it 👍

**Comment by devigned** [comment]
Unfortunately, I'm not going to be able to make this occurrence due to proctoring a workshop at GopherCon. I'll try to catch up async.
